<?php return [
  'Autoloader'      => 'Modules/Application/Autoloader/Autoloader.php',
  'Auth'            => 'Modules/Auth/Auth.php',
  'DBConnector'     => 'Modules/Application/Database/DBConnector.php',
  'DBData'          => 'Modules/Application/Database/DBData.php',
  'UserModel'       => 'Modules/Application/Database/tables/UserModel.php',
  'QueryBox'        => 'Modules/Application/QueryBox/QueryBox.php',
  'UserEntity'      => 'Modules/Auth/UserEntity.php',
  'AuthResponse'    => 'Modules/Auth/AuthResponse.php',
  'Response'        => 'Modules/Application/Response/Response.php',
  'Lobby'           => 'Modules/Lobby/Lobby.php',
  'LobbyEntity'     => 'Modules/Lobby/LobbyEntity.php',
  'LobbyResponse'   => 'Modules/Lobby/LobbyResponse.php',
  'LobbyModel'      => 'Modules/Application/Database/tables/LobbyModel.php',
];